# Generated by Django 4.2.7 on 2026-02-04 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_status_submittedby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelTable(
            name='event',
            table='events',
        ),
    ]
