# Generated by Django 4.2 on 2026-02-18 22:58

from django.db import migrations, models
import events.models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0004_standardize_table_names"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(validators=[events.models.validate_future_date]),
        ),
    ]
