# Generated by Django 4.2 on 2026-02-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_standardize_table_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="failed_login_attempts",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="lockout_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
